# Generated by Django 4.2.6 on 2024-07-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_registration", models.DateField()),
                ("company_registration_number", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_person", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=20)),
                ("email_address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "employee_id_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("department", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("date_started", models.DateField()),
                ("date_left", models.DateField(blank=True, null=True)),
                ("duties", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_employees",
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
