# Generated by Django 4.2.6 on 2024-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="company_id",
            new_name="company",
        ),
    ]
