# Generated by Django 4.2.6 on 2024-07-08 11:16


from django.db import migrations

def update_company_field(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for employee in Employee.objects.all():
        employee.company = employee.company_id
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_company_id_employee_company'),
    ]

    operations = [
        migrations.RunPython(update_company_field),
    ]