# Generated by Django 4.2.6 on 2024-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20240708_1316'),
    ]

    operations = [
        # Remove this entire section
    ]