# Generated by Django 4.2.6 on 2024-07-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_employees_delete_employee"),
        ("employees", "0004_auto_20240708_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="company.company",
            ),
        ),
    ]
